server:
  port: 9000

#服务名称
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15216030332/config-cloud
          username: 15216030332
          password: Jzc19920320
          #超时时间
          timeout: 5
          #分支
          #default-label: test

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/